### ISSUE TITLE
Crash during conversion when there is an empty asset (mp3)

### ISSUE THREAD

**Issue by schmurtzm** [kairoh/studio#6] opened 2022-04-16 22:33 UTC
**Describe the bug**
Crash during conversion when there is an empty asset.
Does not work on 0.4.0 or 0.4.1.
Works fine on 0.3.1.

**To Reproduce**
1 - create the simpliest pack with Studio-Pack-Generator  : 
📂 Story folder
└── 📂 Choose a story   
    ├── 🎵 the story 1.mp3  
    ├── 🎵 the story 2.mp3    
    └── 🎵 the story 3.mp3  
2. import it in studio
3. try to convert it (same result with v1 or V2)
4. See error : "Échec de la conversion du pack d'histoires dans la bibliothèque."

**Expected behavior**
No crash when no mp3 is set on a node

**Screenshots**

**Logs**
<details>
  <summary>log : Click to expand!</summary>
```

2022-04-17 00:09:59,893 [INFO ] [s.m.DatabaseMetadataService]: Reading unofficial database in C:\Users\Schmurtz\.studio\db\unofficial.json
2022-04-17 00:09:59,956 [INFO ] [s.w.s.StoryTellerService]: Setting up story teller driver
2022-04-17 00:09:59,960 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Registering hotplug listener
2022-04-17 00:09:59,963 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2022-04-17 00:09:59,983 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2022-04-17 00:09:59,983 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2022-04-17 00:09:59,988 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Registering hotplug listener
2022-04-17 00:09:59,989 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2022-04-17 00:09:59,990 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2022-04-17 00:09:59,990 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2022-04-17 00:10:00,052 [INFO ] [s.d.LibUsbActivePollingWorker]: Active polling found a new device. Firing event.
2022-04-17 00:10:00,057 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Waiting for device partition...
2022-04-17 00:10:00,307 [INFO ] [s.w.MainVerticle]: Opening URL in default browser...
2022-04-17 00:10:00,593 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle
2022-04-17 00:10:01,072 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Looking for .md in C:\
2022-04-17 00:10:01,073 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Looking for .md in D:\
2022-04-17 00:10:01,074 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Looking for .md in E:\
2022-04-17 00:10:01,074 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Looking for .md in F:\
2022-04-17 00:10:01,075 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Looking for .md in G:\
2022-04-17 00:10:01,076 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Looking for .md in H:\
2022-04-17 00:10:01,077 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Looking for .md in I:\
2022-04-17 00:10:01,077 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Looking for .md in J:\
2022-04-17 00:10:01,078 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Looking for .md in K:\
2022-04-17 00:10:01,079 [INFO ] [s.d.f.FsStoryTellerAsyncDriver]: FS device partition located: K:\
2022-04-17 00:10:01,079 [INFO ] [s.w.s.StoryTellerService]: Device 2.x plugged
2022-04-17 00:10:01,084 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Reading device infos from file: K:\.md
2022-04-17 00:10:01,085 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Device metadata format version: 3
2022-04-17 00:10:01,086 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Firmware version: 2.7
2022-04-17 00:10:01,087 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Serial Number: XXXXXXXXXXXXXXXXXXXXXXXX
2022-04-17 00:10:01,088 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: UUID: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
2022-04-17 00:10:01,107 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card used : 0.0% (56.0 KB / 14.82 GB)
2022-04-17 00:10:01,787 [ERROR] [s.w.MainVerticle]: Exception thrown
io.netty.channel.StacklessClosedChannelException
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
2022-04-17 00:10:01,789 [WARN ] [i.v.e.w.h.i.ErrorHandlerImpl]: Response headers are already written
io.netty.channel.StacklessClosedChannelException
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
2022-04-17 00:10:01,871 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Reading device infos from file: K:\.md
2022-04-17 00:10:01,873 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Device metadata format version: 3
2022-04-17 00:10:01,873 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Firmware version: 2.7
2022-04-17 00:10:01,873 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Serial Number: 9223372036854775807
2022-04-17 00:10:01,873 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: UUID: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
2022-04-17 00:10:01,874 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card used : 0.0% (56.0 KB / 14.82 GB)
2022-04-17 00:10:01,890 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Reading packs index from file: K:\.pi
2022-04-17 00:10:01,891 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Number of packs in index: 0
2022-04-17 00:10:01,894 [INFO ] [s.w.a.EvergreenController]: Current version infos: {"version":"0.4.1","timestamp":"2022-04-04T18:31:18Z"}
2022-04-17 00:10:01,908 [INFO ] [s.w.s.LibraryService]: Read metadata from `test-1650146089327.zip`
2022-04-17 00:10:02,005 [INFO ] [s.w.a.LibraryController]: Library packs scanned in 111ms
2022-04-17 00:10:10,002 [INFO ] [s.w.s.LibraryService]: Pack is in ARCHIVE format. Converting to FS format
2022-04-17 00:10:10,004 [INFO ] [s.w.s.LibraryService]: Reading ARCHIVE format pack
2022-04-17 00:10:10,104 [INFO ] [s.w.s.LibraryService]: Converting assets if necessary
2022-04-17 00:10:10,108 [DEBUG] [s.c.v.u.PackAssetsCompression]: Image from node 1/6 [pack-converter-0]
2022-04-17 00:10:10,109 [DEBUG] [s.c.v.u.PackAssetsCompression]: Image from node 3/6 [ForkJoinPool.commonPool-worker-1]
2022-04-17 00:10:10,108 [DEBUG] [s.c.v.u.PackAssetsCompression]: Image from node 2/6 [ForkJoinPool.commonPool-worker-2]
2022-04-17 00:10:10,110 [DEBUG] [s.c.v.u.PackAssetsCompression]: Image from node 6/6 [ForkJoinPool.commonPool-worker-4]
2022-04-17 00:10:10,111 [DEBUG] [s.c.v.u.PackAssetsCompression]: Converting image asset into 4-bits/RLE BMP
2022-04-17 00:10:10,109 [DEBUG] [s.c.v.u.PackAssetsCompression]: Image from node 4/6 [ForkJoinPool.commonPool-worker-3]
2022-04-17 00:10:10,109 [DEBUG] [s.c.v.u.PackAssetsCompression]: Converting image asset into 4-bits/RLE BMP
2022-04-17 00:10:10,109 [DEBUG] [s.c.v.u.PackAssetsCompression]: Image from node 5/6 [pack-converter-0]
2022-04-17 00:10:10,113 [DEBUG] [s.c.v.u.PackAssetsCompression]: Converting image asset into 4-bits/RLE BMP
2022-04-17 00:10:10,112 [DEBUG] [s.c.v.u.PackAssetsCompression]: Converting image asset into 4-bits/RLE BMP
2022-04-17 00:10:10,529 [DEBUG] [s.c.v.u.PackAssetsCompression]: Audio from node 1/6 [pack-converter-0]
2022-04-17 00:10:10,529 [DEBUG] [s.c.v.u.PackAssetsCompression]: Audio from node 4/6 [ForkJoinPool.commonPool-worker-2]
2022-04-17 00:10:10,529 [DEBUG] [s.c.v.u.PackAssetsCompression]: Audio from node 2/6 [ForkJoinPool.commonPool-worker-4]
2022-04-17 00:10:10,529 [DEBUG] [s.c.v.u.PackAssetsCompression]: Audio from node 6/6 [ForkJoinPool.commonPool-worker-5]
2022-04-17 00:10:10,529 [DEBUG] [s.c.v.u.PackAssetsCompression]: Audio from node 5/6 [ForkJoinPool.commonPool-worker-1]
2022-04-17 00:10:10,531 [DEBUG] [s.c.v.u.PackAssetsCompression]: Audio from node 3/6 [ForkJoinPool.commonPool-worker-3]
2022-04-17 00:10:10,620 [DEBUG] [s.c.v.u.ID3Tags]: Removing ID3v2 tag at beginning of file (45 bytes).
2022-04-17 00:10:10,630 [DEBUG] [s.c.v.u.ID3Tags]: Removing ID3v2 tag at beginning of file (45 bytes).
2022-04-17 00:10:10,684 [INFO ] [s.w.s.LibraryService]: Writing FS format pack, using temporary folder: C:\Users\Schmurtz\.studio\tmp\test-1650146089327.zip13923290999385380397
2022-04-17 00:10:10,740 [ERROR] [s.w.s.LibraryService]: Failed to convert ARCHIVE format pack to FS format
java.lang.IllegalArgumentException: Unsupported Audio File
        at studio.core.v1.writer.fs.FsStoryPackWriter.write(FsStoryPackWriter.java:185)
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:258)
        at studio.webui.service.LibraryService.addConvertedPack(LibraryService.java:154)
        at studio.webui.api.LibraryController.lambda$apiRouter$4(LibraryController.java:92)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.sound.sampled.UnsupportedAudioFileException: Stream of unsupported format
        at java.desktop/javax.sound.sampled.AudioSystem.getAudioFileFormat(AudioSystem.java:926)
        at studio.core.v1.writer.fs.FsStoryPackWriter.write(FsStoryPackWriter.java:179)
        ... 11 more
2022-04-17 00:10:10,746 [ERROR] [s.w.a.LibraryController]: Failed to read or convert pack
2022-04-17 00:10:10,747 [ERROR] [s.w.MainVerticle]: Exception thrown
studio.core.v1.utils.exception.StoryTellerException: Failed to convert ARCHIVE format pack to FS format
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:269)
        at studio.webui.service.LibraryService.addConvertedPack(LibraryService.java:154)
        at studio.webui.api.LibraryController.lambda$apiRouter$4(LibraryController.java:92)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Unsupported Audio File
        at studio.core.v1.writer.fs.FsStoryPackWriter.write(FsStoryPackWriter.java:185)
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:258)
        ... 10 more
Caused by: javax.sound.sampled.UnsupportedAudioFileException: Stream of unsupported format
        at java.desktop/javax.sound.sampled.AudioSystem.getAudioFileFormat(AudioSystem.java:926)
        at studio.core.v1.writer.fs.FsStoryPackWriter.write(FsStoryPackWriter.java:179)
        ... 11 more
2022-04-17 00:10:10,767 [ERROR] [s.w.MainVerticle]: Exception thrown
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:216)
        at java.base/java.nio.file.Path.resolve(Path.java:515)
        at studio.webui.api.DeviceController.lambda$apiRouter$11(DeviceController.java:59)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
```
</details>

**Desktop and environment (please complete the following information):**
 - OS:  Win 10
 - Browser Firefox
 - Java version:  JDK 18
 - Maven version: ?
 - STUdio application version : 0.4.1



Thanks for this great software ;)

**Comment by kairoh** [comment] 2022-04-25 19:16
Duplicate of #5

**Closed by kairoh** 2022-04-25 19:16 UTC
Labels: bug, duplicate
